---
title: Wanasa Kitchen
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: sections
  values:
    tagline: ''
    box_body: ''
    images: []
url: https://wanasacafe.co.uk
Instagram: wanasakitchen
Menus:
- title: Breakfast Menu
  file: "/uploads/wanasa-breakfast-menu-490f4d.pdf"
  Key: 
- title: Brunch Menu
  file: "/uploads/wanasa-lunch-menu-352b15.pdf"
- title: For Kids
  file: "/uploads/wanasa-kids-menu-bf706b.pdf"
  Key: 
- title: Drinks
  file: "/uploads/wanasa-drinks-menu-3310f2.pdf"
- title: Teas
  file: "/uploads/wanasa-tea-menu-03e326.pdf"
